// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#include "test.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_test_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ProtoTestSub_test_2eproto;
namespace msgType {
class ProtoTestSubDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ProtoTestSub> _instance;
} _ProtoTestSub_default_instance_;
class ProtoTestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ProtoTest> _instance;
} _ProtoTest_default_instance_;
}  // namespace msgType
static void InitDefaultsscc_info_ProtoTest_test_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::msgType::_ProtoTest_default_instance_;
    new (ptr) ::msgType::ProtoTest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::msgType::ProtoTest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ProtoTest_test_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ProtoTest_test_2eproto}, {
      &scc_info_ProtoTestSub_test_2eproto.base,}};

static void InitDefaultsscc_info_ProtoTestSub_test_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::msgType::_ProtoTestSub_default_instance_;
    new (ptr) ::msgType::ProtoTestSub();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::msgType::ProtoTestSub::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ProtoTestSub_test_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ProtoTestSub_test_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_test_2eproto[2];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_test_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_test_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_test_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::msgType::ProtoTestSub, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::msgType::ProtoTestSub, test1_),
  PROTOBUF_FIELD_OFFSET(::msgType::ProtoTestSub, test2_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::msgType::ProtoTest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::msgType::ProtoTest, int32_test_),
  PROTOBUF_FIELD_OFFSET(::msgType::ProtoTest, str_test_),
  PROTOBUF_FIELD_OFFSET(::msgType::ProtoTest, dou_test_),
  PROTOBUF_FIELD_OFFSET(::msgType::ProtoTest, sub_test_),
  PROTOBUF_FIELD_OFFSET(::msgType::ProtoTest, enum_test_),
  PROTOBUF_FIELD_OFFSET(::msgType::ProtoTest, bytes_test_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::msgType::ProtoTestSub)},
  { 7, -1, sizeof(::msgType::ProtoTest)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::msgType::_ProtoTestSub_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::msgType::_ProtoTest_default_instance_),
};

const char descriptor_table_protodef_test_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\ntest.proto\022\007msgType\",\n\014ProtoTestSub\022\r\n"
  "\005test1\030\001 \001(\005\022\r\n\005test2\030\002 \001(\t\"\246\001\n\tProtoTes"
  "t\022\022\n\nint32_test\030\001 \001(\005\022\020\n\010str_test\030\002 \001(\t\022"
  "\020\n\010dou_test\030\003 \003(\001\022\'\n\010sub_test\030\004 \003(\0132\025.ms"
  "gType.ProtoTestSub\022$\n\tenum_test\030\005 \001(\0162\021."
  "msgType.EnumTest\022\022\n\nbytes_test\030\006 \001(\014*6\n\010"
  "EnumTest\022\t\n\005TEST0\020\000\022\t\n\005TEST1\020\001\022\t\n\005TEST2\020"
  "\002\022\t\n\005TEST3\020\003b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_test_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_test_2eproto_sccs[2] = {
  &scc_info_ProtoTest_test_2eproto.base,
  &scc_info_ProtoTestSub_test_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_test_2eproto_once;
static bool descriptor_table_test_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_test_2eproto = {
  &descriptor_table_test_2eproto_initialized, descriptor_table_protodef_test_2eproto, "test.proto", 300,
  &descriptor_table_test_2eproto_once, descriptor_table_test_2eproto_sccs, descriptor_table_test_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_test_2eproto::offsets,
  file_level_metadata_test_2eproto, 2, file_level_enum_descriptors_test_2eproto, file_level_service_descriptors_test_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_test_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_test_2eproto)), true);
namespace msgType {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EnumTest_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_test_2eproto);
  return file_level_enum_descriptors_test_2eproto[0];
}
bool EnumTest_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void ProtoTestSub::InitAsDefaultInstance() {
}
class ProtoTestSub::_Internal {
 public:
};

ProtoTestSub::ProtoTestSub()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:msgType.ProtoTestSub)
}
ProtoTestSub::ProtoTestSub(const ProtoTestSub& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  test2_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_test2().empty()) {
    test2_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.test2_);
  }
  test1_ = from.test1_;
  // @@protoc_insertion_point(copy_constructor:msgType.ProtoTestSub)
}

void ProtoTestSub::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ProtoTestSub_test_2eproto.base);
  test2_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  test1_ = 0;
}

ProtoTestSub::~ProtoTestSub() {
  // @@protoc_insertion_point(destructor:msgType.ProtoTestSub)
  SharedDtor();
}

void ProtoTestSub::SharedDtor() {
  test2_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ProtoTestSub::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ProtoTestSub& ProtoTestSub::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ProtoTestSub_test_2eproto.base);
  return *internal_default_instance();
}


void ProtoTestSub::Clear() {
// @@protoc_insertion_point(message_clear_start:msgType.ProtoTestSub)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  test2_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  test1_ = 0;
  _internal_metadata_.Clear();
}

const char* ProtoTestSub::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 test1 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          test1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string test2 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_test2();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "msgType.ProtoTestSub.test2"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ProtoTestSub::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:msgType.ProtoTestSub)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 test1 = 1;
  if (this->test1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_test1(), target);
  }

  // string test2 = 2;
  if (this->test2().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_test2().data(), static_cast<int>(this->_internal_test2().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "msgType.ProtoTestSub.test2");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_test2(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:msgType.ProtoTestSub)
  return target;
}

size_t ProtoTestSub::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:msgType.ProtoTestSub)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string test2 = 2;
  if (this->test2().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_test2());
  }

  // int32 test1 = 1;
  if (this->test1() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_test1());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ProtoTestSub::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:msgType.ProtoTestSub)
  GOOGLE_DCHECK_NE(&from, this);
  const ProtoTestSub* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ProtoTestSub>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:msgType.ProtoTestSub)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:msgType.ProtoTestSub)
    MergeFrom(*source);
  }
}

void ProtoTestSub::MergeFrom(const ProtoTestSub& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:msgType.ProtoTestSub)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.test2().size() > 0) {

    test2_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.test2_);
  }
  if (from.test1() != 0) {
    _internal_set_test1(from._internal_test1());
  }
}

void ProtoTestSub::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:msgType.ProtoTestSub)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProtoTestSub::CopyFrom(const ProtoTestSub& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:msgType.ProtoTestSub)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtoTestSub::IsInitialized() const {
  return true;
}

void ProtoTestSub::InternalSwap(ProtoTestSub* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  test2_.Swap(&other->test2_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(test1_, other->test1_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ProtoTestSub::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ProtoTest::InitAsDefaultInstance() {
}
class ProtoTest::_Internal {
 public:
};

ProtoTest::ProtoTest()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:msgType.ProtoTest)
}
ProtoTest::ProtoTest(const ProtoTest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      dou_test_(from.dou_test_),
      sub_test_(from.sub_test_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  str_test_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_str_test().empty()) {
    str_test_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.str_test_);
  }
  bytes_test_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_bytes_test().empty()) {
    bytes_test_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.bytes_test_);
  }
  ::memcpy(&int32_test_, &from.int32_test_,
    static_cast<size_t>(reinterpret_cast<char*>(&enum_test_) -
    reinterpret_cast<char*>(&int32_test_)) + sizeof(enum_test_));
  // @@protoc_insertion_point(copy_constructor:msgType.ProtoTest)
}

void ProtoTest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ProtoTest_test_2eproto.base);
  str_test_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  bytes_test_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&int32_test_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&enum_test_) -
      reinterpret_cast<char*>(&int32_test_)) + sizeof(enum_test_));
}

ProtoTest::~ProtoTest() {
  // @@protoc_insertion_point(destructor:msgType.ProtoTest)
  SharedDtor();
}

void ProtoTest::SharedDtor() {
  str_test_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  bytes_test_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ProtoTest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ProtoTest& ProtoTest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ProtoTest_test_2eproto.base);
  return *internal_default_instance();
}


void ProtoTest::Clear() {
// @@protoc_insertion_point(message_clear_start:msgType.ProtoTest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  dou_test_.Clear();
  sub_test_.Clear();
  str_test_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  bytes_test_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&int32_test_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&enum_test_) -
      reinterpret_cast<char*>(&int32_test_)) + sizeof(enum_test_));
  _internal_metadata_.Clear();
}

const char* ProtoTest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 int32_test = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          int32_test_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string str_test = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_str_test();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "msgType.ProtoTest.str_test"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated double dou_test = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_dou_test(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 25) {
          _internal_add_dou_test(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // repeated .msgType.ProtoTestSub sub_test = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_sub_test(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      // .msgType.EnumTest enum_test = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_enum_test(static_cast<::msgType::EnumTest>(val));
        } else goto handle_unusual;
        continue;
      // bytes bytes_test = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_bytes_test();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ProtoTest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:msgType.ProtoTest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 int32_test = 1;
  if (this->int32_test() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_int32_test(), target);
  }

  // string str_test = 2;
  if (this->str_test().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_str_test().data(), static_cast<int>(this->_internal_str_test().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "msgType.ProtoTest.str_test");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_str_test(), target);
  }

  // repeated double dou_test = 3;
  if (this->_internal_dou_test_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_dou_test(), target);
  }

  // repeated .msgType.ProtoTestSub sub_test = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_sub_test_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_sub_test(i), target, stream);
  }

  // .msgType.EnumTest enum_test = 5;
  if (this->enum_test() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      5, this->_internal_enum_test(), target);
  }

  // bytes bytes_test = 6;
  if (this->bytes_test().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        6, this->_internal_bytes_test(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:msgType.ProtoTest)
  return target;
}

size_t ProtoTest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:msgType.ProtoTest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double dou_test = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_dou_test_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _dou_test_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated .msgType.ProtoTestSub sub_test = 4;
  total_size += 1UL * this->_internal_sub_test_size();
  for (const auto& msg : this->sub_test_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string str_test = 2;
  if (this->str_test().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_str_test());
  }

  // bytes bytes_test = 6;
  if (this->bytes_test().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_bytes_test());
  }

  // int32 int32_test = 1;
  if (this->int32_test() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_int32_test());
  }

  // .msgType.EnumTest enum_test = 5;
  if (this->enum_test() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_enum_test());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ProtoTest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:msgType.ProtoTest)
  GOOGLE_DCHECK_NE(&from, this);
  const ProtoTest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ProtoTest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:msgType.ProtoTest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:msgType.ProtoTest)
    MergeFrom(*source);
  }
}

void ProtoTest::MergeFrom(const ProtoTest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:msgType.ProtoTest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  dou_test_.MergeFrom(from.dou_test_);
  sub_test_.MergeFrom(from.sub_test_);
  if (from.str_test().size() > 0) {

    str_test_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.str_test_);
  }
  if (from.bytes_test().size() > 0) {

    bytes_test_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.bytes_test_);
  }
  if (from.int32_test() != 0) {
    _internal_set_int32_test(from._internal_int32_test());
  }
  if (from.enum_test() != 0) {
    _internal_set_enum_test(from._internal_enum_test());
  }
}

void ProtoTest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:msgType.ProtoTest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProtoTest::CopyFrom(const ProtoTest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:msgType.ProtoTest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtoTest::IsInitialized() const {
  return true;
}

void ProtoTest::InternalSwap(ProtoTest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  dou_test_.InternalSwap(&other->dou_test_);
  sub_test_.InternalSwap(&other->sub_test_);
  str_test_.Swap(&other->str_test_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  bytes_test_.Swap(&other->bytes_test_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(int32_test_, other->int32_test_);
  swap(enum_test_, other->enum_test_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ProtoTest::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace msgType
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::msgType::ProtoTestSub* Arena::CreateMaybeMessage< ::msgType::ProtoTestSub >(Arena* arena) {
  return Arena::CreateInternal< ::msgType::ProtoTestSub >(arena);
}
template<> PROTOBUF_NOINLINE ::msgType::ProtoTest* Arena::CreateMaybeMessage< ::msgType::ProtoTest >(Arena* arena) {
  return Arena::CreateInternal< ::msgType::ProtoTest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
